name: Sander Studio
favicon: null
layout_spectrum: 0.10775870992802083
typography_spectrum: 0.07003801711834967
title: Sander Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8119478018488735
  lightness: 0.2149675579275936
  saturation: 0.05711901979520917
  rhythmicContrast: 0.8182091945782304
purpose: []
