name: Sander Studio
favicon: null
layout_spectrum: 0.10775870992802083
typography_spectrum: 0.07003801711834967
title: Sander Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cc9060'
    - '#f90000'
    - '#1c6261'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
